default_language_version:
  python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
    -   id: nbqa-isort

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: [--profile, black]
        types_or: [python, pyi, jupyter]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length", "88"]
        types_or: [python, pyi, jupyter]


-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.7'
    hooks:
    -   id: ruff
        types_or: [python, pyi, jupyter]
        args: [ --fix, --exit-non-zero-on-fix ]
